language: r

repos:
  CRAN: https://cloud.r-project.org
  folkehelseinstituttet: https://folkehelseinstituttet.github.io/drat/
  euromomo: https://euromomonetwork.github.io/drat/
  raubreywhite: https://raubreywhite.github.io/drat/

r_packages:
- covr
- drat
- pkgdown
- styler
- devtools

before_install:
- Rscript -e 'devtools::install_github("HenrikBengtsson/progressr")'
- bash travis/make.sh

after_success:
- Rscript -e 'library(covr); codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  travis/drat.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  travis/styler.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && Rscript
  -e 'Sys.sleep(30);install.packages("plnr",repos="https://folkehelseinstituttet.github.io/drat/");pkgdown::build_site()'
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    branch: master
